# a directory to store all tools
store_directory = "~/.toolsync/bin"

# the following tools will be installed in 'store_directory'
[bat]
[difftastic]
[exa]
[fd]
[ripgrep]

[gitui]
owner = "extrawurst"
repo = "gitui"
exe_name = "gitui"
asset_name.macos = "mac.tar.gz"